# Generated by Django 3.0.6 on 2020-05-22 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginentry',
            name='time',
            field=models.DateField(default=datetime.datetime(2020, 5, 22, 15, 14, 14, 861699, tzinfo=utc)),
        ),
    ]
