# Generated by Django 3.0.6 on 2020-05-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='is_healthy',
            field=models.BooleanField(default=False),
        ),
    ]
